before_script:
  - yarn install --frozen-lockfile #--frozen-lockfile to make sure we will have the same packages version

stages:
  - build

build project:
  stage: build
  image: reactnativecommunity/react-native-android
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: pull #`pull` the jobs pull the cache at the beginning but do not push the changes again.
  script:
    - cd android && ./gradlew assembleRelease # is the scripts defined in your package.json as "cd android #&& ./gradlew assembleRelease"
    
  artifacts:
    paths:
      - android/app/build/outputs/apk/release/app-release.apk