export const REQUEST_UPDATED = 'REQUEST_UPDATED'
export const WAITING_REQUEST_UPDATED = 'WAITING_REQUEST_UPDATED'
export const REQUEST_COMPLETED = 'REQUEST_COMPLETED'
export const REQUEST_IN_PROGRESS_ACTION = 'REQUEST_IN_PROGRESS_ACTION'
export const SETTINGS_UPDATED = 'SETTINGS_UPDATED'
export const PROVIDER_PROFILE_UPDATED = 'PROVIDER_PROFILE_UPDATED'
export const LOAD_AUDIO_REQUEST_BEEP = 'LOAD_AUDIO_REQUEST_BEEP'
export const LOAD_AUDIO_CANCELLATION_BEEP = 'LOAD_AUDIO_CANCELLATION_BEEP'
export const LOAD_AUDIO_CHAT_PROVIDER = 'LOAD_AUDIO_CHAT_PROVIDER'
export const ENABLED_LANGUAGES = 'ENABLED_LANGUAGES'
export const APPLICATION_PAGES = 'APPLICATION_PAGES'
export const SET_TOGGLESWITCH = 'SET_TOGGLESWITCH'
export const ACTIVE_DESTINATION = 'ACTIVE_DESTINATION'
export const ACTIVE_FULLADDRESS = 'ACTIVE_FULLADDRESS'
export const ACTIVE_LATITUDE = 'ACTIVE_LATITUDE'
export const ACTIVE_LONGITUDE = 'ACTIVE_LONGITUDE'
export const CLICKER_UPDATED = 'CLICKER_UPDATED'
export const SET_REQUEST_NOTICE = 'SET_REQUEST_NOTICE'
export const WAITING_SET_REQUEST_NOTICE = 'WAITING_SET_REQUEST_NOTICE'
export const RECEIVE_NOTICE = 'RECEIVE_NOTICE'
export const WAITING_RECEIVE_NOTICE = 'WAITING_RECEIVE_NOTICE'

export const SET_SOURCE = 'SET_SOURCE';
export const SET_DESTINATION = 'SET_DESTINATION';
export const CLEAR_ADRESSES = 'CLEAR_ADRESSES';
export const SET_CATEGORYID = 'SET_CATEGORYID';

export const SET_SERVICE = 'SET_SERVICE';
export const SET_INDEX = 'SET_INDEX';
export const SET_TYPEID = 'SET_TYPEID';
export const SET_CATEGORIES = 'SET_CATEGORIES';

export const CLEAR_ESTIMATIVE = 'CLEAR_ESTIMATIVE';

export const PAYMENT_NOMENCLATURES = 'PAYMENT_NOMENCLATURES';

export const CLEAR_STOPS = 'CLEAR_STOPS';
export const SET_STOP = 'SET_STOP';
export const REMOVE_STOP = 'REMOVE_STOP';
//sig data
export const SET_SIG_DATA = 'SET_SIG_DATA';