require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '12.0'
use_modular_headers!

target 'UberCloneProvider' do
  pod 'CocoaAsyncSocket', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'UberCloneProviderTests' do
    inherit! :complete
    # Pods for testing
  end

end

target 'UberCloneProvider-tvOS' do
  # Pods for UberCloneProvider-tvOS

  target 'UberCloneProvider-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end